Yemek_Tarif_Core_MVC/Controllers/CommentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Xml.Linq;

namespace Yemek_Tarif_Core_MVC.Controllers
{
    [AllowAnonymous]
    public class CommentController : Controller
    {
        CommentManager cm = new(new EFCommentRepository());
        public IActionResult Index()
        {
            return View();
        }
        public PartialViewResult PartialAddComment(int RecipeID)
        {
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult PartialAddComment(/*Comment p,*//*int RecipeID,*/ /*string txtName,string txtEmail,string txtKonu,string txtMesaj*/ [FromBody] Comment p,int like )
        {
            p.CommentDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.CommentStatus = true;
            p.RecipeScore = like;
            //p.ReceipeID=
            //int like = Convert.ToInt32(Request.Form["like"]);
            cm.CommentAdd(p);
            return PartialView();
        }
        public PartialViewResult CommentListByBlog(int id)
        {
            var values=cm.GetList(id);
            return PartialView(values);
        }
        public IActionResult Deneme()
        {
            return View();
        }
    }
}

Yemek_Tarif_Core_MVC/Views/Comment/CommentListByBlog.cshtml
<div class="comment-top">
	<h4>Yorumlar</h4>
	<div class="media">
		<img src="images/t1.jpg" alt="" class="img-fluid" />
		<div class="media-body">
			<h5 class="mt-0">Joseph Goh</h5>
			<p>
				Bu tarifi gerçekten çok beğendim. Haftada bir kaç defa kendi yaptığım yemeklere de uygulamak istiyorum. Teşekkür ederim
			</p>

			<div class="media mt-3">
				<a class="d-flex pr-3" href="#">
					<img src="images/t2.jpg" alt="" class="img-fluid" />
				</a>
				<div class="media-body">
					<h5 class="mt-0">Richard Spark</h5>
					<p>
						Ben de aynı fikirdeyim fakat ölçüleri kendinize göre ayarlamanızda fayda var. Aksi taktirde ölçüler biraz fazla kaçabilir
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

Yemek_Tarif_Core_MVC/Views/Comment/CommentListByRecipe.cshtml
@*@model IEnumerable<EntityLayer.Concrete.Comment>*@
@*@model List<EntityLayer.Concrete.Recipe>*@


<div class="comment-top">
	<h4>Yorumlar</h4>
	<div class="media">
		<img src="images/t1.jpg" alt="" class="img-fluid" />
		<div class="media-body">
			<h5 class="mt-0">Joseph Goh</h5>
			<p>
				Bu tarifi gerçekten çok beğendim. Haftada bir kaç defa kendi yaptığım yemeklere de uygulamak istiyorum. Teşekkür ederim
			</p>

			<div class="media mt-3">
				<a class="d-flex pr-3" href="#">
					<img src="images/t2.jpg" alt="" class="img-fluid" />
				</a>
				<div class="media-body">
					<h5 class="mt-0">Richard Spark</h5>
					<p>
						Ben de aynı fikirdeyim fakat ölçüleri kendinize göre ayarlamanızda fayda var. Aksi taktirde ölçüler biraz fazla kaçabilir
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

Yemek_Tarif_Core_MVC/Views/Comment/PartialAddComment.cshtml
@model int // RecipeReadAll view'inden gönderdiğimiz modeli burada alıyoruz
<br />

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<link href="~/writer/assets/css/reciperayting.css" rel="stylesheet" />
<div class="comment-top">
    <h3>Sen de bir yorum yazmak ister misin?</h3>

    <div class="comment-bottom">
        <form action="/Comment/PartialAddComment" method="post">

       @*  @using (Html.BeginForm("PartialAddComment", "Comment", FormMethod.Post))
        { *@
            @*action="/Comment/PartialAddComment" method="post"*@
            <input class="form-control" type="text" name="Name" id="Name" placeholder="İsim" required="">

            <br />
            <input class="form-control" type="email" name="Email" id="Email" placeholder="E-mail" required="">

            <br />

            <input class="form-control" type="text" name="Subject" id="Subject" placeholder="Konu" required="">

            <br />
            <input type="hidden" name="RecipeID" id="RecipeID" value="@Model" />
            @*Modelden gelen parametreyi burada  Controller'a gönderiyoruz*@
            <textarea class="form-control" name="Message" id="Message" placeholder="Mesaj..." required=""></textarea>

            <br />
            <section id="like" class="rating">
                <!-- FIFTH HEART -->
                <input type="radio" id="heart_5" name="like" value="5" />
                <label for="heart_5" title="Five">&#10084;</label>
                <!-- FOURTH HEART -->
                <input type="radio" id="heart_4" name="like" value="4" />
                <label for="heart_4" title="Four">&#10084;</label>
                <!-- THIRD HEART -->
                <input type="radio" id="heart_3" name="like" value="3" />
                <label for="heart_3" title="Three">&#10084;</label>
                <!-- SECOND HEART -->
                <input type="radio" id="heart_2" name="like" value="2" />
                <label for="heart_2" title="Two">&#10084;</label>
                <!-- FIRST HEART -->
                <input type="radio" id="heart_1" name="like" value="1" />
                <label for="heart_1" title="One">&#10084;</label>
            </section>
            <button type="submit" id="btnSave" class="btn btn-primary submit">Gönder</button>
        @* } *@
        </form>



    </div>
</div>
<script>
    $(document).ready(function () {
        $('#btnSave').click(function (event) {
            event.preventDefault();
            var recipeID = $('#RecipeID').val();
        var like = $("input[name='like']:checked").val();
            var p = {
                CommentUserName: $('#Name').val(),
                CommentTitle: $('#Subject').val(),
                CommentContent: $('#Message').val(),
                RecipeID: $('#RecipeID').val()
            };
            var url = '/Comment/PartialAddComment?like=' + like;
            $.ajax({
                url: url,
                type: 'POST',
                dataType:'JSON',
                data: JSON.stringify(p), 
                contentType: 'application/json',
                success: function (data) {
                    window.location.href = 'Recipe/RecipeReadAll' + recipeID;
                    console.log(data);
                },
                error: function () {

                }
            });
        });
    
    });
</script>