Yemek_Tarif_Core_MVC/Controllers/MessageController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Security.Claims;

namespace Yemek_Tarif_Core_MVC.Controllers
{
    public class MessageController : Controller
    {
        UserManager um = new(new EFUserRepository());
        MessageManager mm = new(new EFMessageRepository());
        public IActionResult Inbox()
        {
            var writerID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var values = mm.GetMessageListWithWriter(int.Parse(writerID));
            return View(values);
        }

        public IActionResult MessageDetail(int id)
        {
            var message = mm.TGetByID(id);
            return PartialView("MessageDetail", message);
        }
        public IActionResult DeleteMessage(int id)
        {
            var message=mm.TGetByID(id);
            message.MessageStatus = false;
            return View();
        }
        [HttpGet]
        public IActionResult SendMessage()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SendMessage(WriterMessage wm, string userName)
        {
            try
            {    
                var senderUser = um.GetSessionByWriter(userName);
                var writerID = User.FindFirstValue(ClaimTypes.NameIdentifier);
                if (senderUser == null)
                {
                    ViewBag.hata = "Kullanıcı Bulunamadı!";
                }
                else
                {
                    wm.SenderID = int.Parse(writerID);
                    wm.ReceiverID = senderUser.Id;
                wm.MessageStatus = true;
                wm.MessageDate = Convert.ToDateTime(DateTime.Now.ToShortDateString());
                    wm.MessageDate=  Convert.ToDateTime(DateTime.Now.ToShortDateString());
                    wm.MessageStatus = true;
                mm.TAdd(wm);
                }
                
                return RedirectToAction("Sendbox");

            }
            catch (Exception s)
            {

                var hata= s.Message.ToString();
                return View();
            }

           
            
        }
        public IActionResult SendBox()
        {
            var writerID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var values = mm.GetSendBoxListByWriter(int.Parse(writerID));
            return View(values);
        }
    }
}

Yemek_Tarif_Core_MVC/Views/Message/Inbox.cshtml
@model List<WriterMessage>
@{
    ViewData["Title"] = "Inbox";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Mesajlarınız</h4>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th> Konu </th>
                        <th> Gönderen</th>
                        <th> Tarih </th>
                        <th> Mesajı Aç </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>
                                @item.Subject
                            </td>
                            <td>
                                @* <img src="@item.SenderWriter.WriterImage" alt="image"> *@
                                @item.SenderWriter.NameSurname
                            </td>
                            <td>
                                @item.MessageDate
                            </td>

                            <td> <a class="btn btn-outline-info" onclick="showMessageDetails('@item.MessageID')">Mesajı Aç</a> </td>
                        </tr>
                    }
                </tbody>
            </table>
            <br />
            <a href="/Message/SendMessage" class="btn btn-outline-primary">Yeni Mesaj Oluştur</a>

        </div>
    </div>
</div>

<div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Mesaj</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="messageDetails">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
            </div>
        </div>
    </div>
</div>

<script>
    function showMessageDetails(messageId) {
        $.ajax({
            url: '/Message/MessageDetail',
            type: 'GET',
            data: { id: messageId },
            success: function (data) {
                // AJAX çağrısı başarılı olduğunda modal içeriğini güncelle
                $('#messageDetails').html(data);
                $('#messageModal').modal('show'); // Modalı göster
            },
            error: function () {

                alert('Mesaj detayları alınamadı.');
            }
        });
    }
</script>

Yemek_Tarif_Core_MVC/Views/Message/MessageDetail.cshtml
@model WriterMessage
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<p>@Model.MessageDetails</p>

Yemek_Tarif_Core_MVC/Views/Message/SendBox.cshtml
@model List<WriterMessage>
@{
    ViewData["Title"] = "SendBox";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}


<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Mesajlarınız</h4>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th> Konu </th>
                        <th> Alıcı</th>
                        <th> Tarih </th>
                        <th> Mesajı Aç </th>
                        <th> Mesajı Sil </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Where(x => x.MessageStatus == true))
                    {

                        <tr>
                            <td>
                                @item.Subject
                            </td>
                            <td>
                                @* <img src="@item.SenderWriter.WriterImage" alt="image"> *@
                                @item.ReceiverWriter.NameSurname
                            </td>
                            <td>
                                @item.MessageDate
                            </td>
                            <td> <a class="btn btn-outline-info" onclick="showMessageDetails('@item.MessageID')">Mesajı Aç</a> </td>
                            <td> <a class="btn btn-outline-danger" onclick="deleteMesseage('@item.MessageID')">Mesajı Sil</a> </td>
                        </tr>
                    }
                </tbody>
            </table>
            <br />
            <a href="/Message/SendMessage" class="btn btn-outline-primary">Yeni Mesaj Oluştur</a>

        </div>
    </div>
</div>

<div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Mesaj</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="messageDetails">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
            </div>
        </div>
    </div>
</div>

<script>
    function deleteMessage(messageId) {
        if (confirm("Yazarı silmek istediğinize emin misiniz?")) {
            $.ajax({
                url: 'Message/DeleteMessage',
                type: 'GET',
                data: { id: messageId },
                succes: function (data) {

                }
            })
        }
    }
    function showMessageDetails(messageId) {
        $.ajax({
            url: '/Message/MessageDetail',
            type: 'GET',
            data: { id: messageId },
            success: function (data) {
                // AJAX çağrısı başarılı olduğunda modal içeriğini güncelle
                $('#messageDetails').html(data);
                $('#messageModal').modal('show'); // Modalı göster
            },
            error: function () {

                alert('Mesaj detayları alınamadı.');
            }
        });
    }
</script>

Yemek_Tarif_Core_MVC/Views/Message/SendMessage.cshtml
@model WriterMessage
@{
    ViewData["Title"] = "SendMessage";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

@using (Html.BeginForm("SendMessage", "Message", FormMethod.Post))
{
    <div class="form-row">
        <div class="col-md-6 mb-3">
            <label for="validationCustom01">Kime?</label>
            <input type="text" class="form-control" name="userName" placeholder="Gönderilecek Kişinin Kullanıcı Adı:">
            @if (ViewBag.hata!=null)
            {
                <span class="text-danger">@ViewBag.hata</span>
            }
           @*  @Html.TextBoxFor(x=>x.Subject,new{@class="form-control"})
            @Html.ValidationMessageFor(x=>x.Subject,"",new{@class="text-danger"}) *@
        </div>
        <div class="col-md-6 mb-3">
            <label for="validationCustom01">Mesaj Konusu</label>
            @Html.TextBoxFor(x=>x.Subject,new{@class="form-control"})
            @Html.ValidationMessageFor(x=>x.Subject,"",new{@class="text-danger"})
        </div>

        <div class="col-md-6 mb-3">
            <label for="validationCustom02">Mesaj Açıklaması</label>
            @Html.TextBoxFor(x=>x.MessageDetails,new{@class="form-control"})
            @Html.ValidationMessageFor(x=>x.MessageDetails,"",new{@class="text-danger"})

        </div>
        
    </div>
    <button class="btn btn-primary">Mesajı Gönder</button>


}